apiVersion: v1
kind: Service
metadata:
  labels:
    app: ocloud-tdmq-rocketmq5-namesrv
    dawn.infra.tce.io/application-instance-name: ocloud-tdmq-rocketmq5-namesrv
    dawn.infra.tce.io/application-instance-uuid: aab75aedd4e059c4a1f3df1d3587ad56
    dawn.infra.tce.io/application-name: ocloud-tdmq-rocketmq5-namesrv
    dawn.infra.tce.io/application-version: 0.1.0-20260120-163941-719acf4
    dawn.infra.tce.io/product-instance-id: tdmq-rocketmq-1
    dawn.infra.tce.io/region-id: "50000001"
    dawn.infra.tce.io/region-name: ap-beijing-region-jcctest-ops
    infra.tce.io/app-version: 0.1.0-20260120-163941-719acf4.rhel.amd64
    infra.tce.io/chart-name: ocloud-tdmq-rocketmq5-namesrv
    infra.tce.io/oam-app: ocloud-tdmq-rocketmq5-namesrv
    infra.tce.io/oam-comp: ocloud-tdmq-rocketmq5-namesrv
    infra.tce.io/oam-product: tdmq-rocketmq
    infra.tce.io/oam-trait: ocloud-tdmq-rocketmq5-namesrv
    infra.tce.io/oam-trait-id: 7a990c04-7321-44e0-91a2-128426a1097f
    rocketmq.version: "4"
  name: ocloud-tdmq-rocketmq5-namesrv
  namespace: tce
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: 9876-tcp
      port: 9876
      protocol: TCP
      targetPort: 9876
    - name: 9880-tcp
      port: 9880
      protocol: TCP
      targetPort: 9880
    - name: 9770-tcp
      port: 9770
      protocol: TCP
      targetPort: 9770
  selector:
    infra.tce.io/oam-app: ocloud-tdmq-rocketmq5-namesrv
    infra.tce.io/oam-comp: ocloud-tdmq-rocketmq5-namesrv
  sessionAffinity: None
  type: ClusterIP