apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    dawn.infra.tce.io/application-instance-name: ocloud-tdmq-rocketmq5-broker
    dawn.infra.tce.io/application-instance-uuid: a2e45275b7cd56e893dcf7fce1fc445c
    dawn.infra.tce.io/application-name: ocloud-tdmq-rocketmq5-broker
    dawn.infra.tce.io/application-version: 0.1.0-20251203-104526-40111ba
    dawn.infra.tce.io/product-instance-id: tdmq-rocketmq-1
    dawn.infra.tce.io/region-id: "50000001"
    dawn.infra.tce.io/region-name: chongqing
    infra.tce.io/app-version: 0.1.0-20251203-104526-40111ba.rhel.amd64
    infra.tce.io/chart-name: ocloud-tdmq-rocketmq5-broker
    infra.tce.io/oam-app: ocloud-tdmq-rocketmq5-broker
    infra.tce.io/oam-comp: ocloud-tdmq-rocketmq5-broker
    infra.tce.io/oam-product: tdmq-rocketmq
    rocketmq.version: "4"
  name: ocloud-tdmq-rocketmq5-broker
  namespace: tce
spec:
  podManagementPolicy: Parallel
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      infra.tce.io/oam-app: ocloud-tdmq-rocketmq5-broker
      infra.tce.io/oam-comp: ocloud-tdmq-rocketmq5-broker
  serviceName: ocloud-tdmq-rocketmq5-broker
  template:
    metadata:
      annotations:
        network.infra.tce.io/ip-reserved: "true"
      creationTimestamp: null
      labels:
        infra.tce.io/oam-app: ocloud-tdmq-rocketmq5-broker
        infra.tce.io/oam-comp: ocloud-tdmq-rocketmq5-broker
        rocketmq.version: "4"
    spec:
      containers:
        - args:
            - broker
          command:
            - ./entrypoint.sh
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: ROCKETMQ_HOME
              value: /root
            - name: RMQ_ID
              value: ocloud-tdmq-rocketmq5-broker
            - name: RAINBOW_ENV
              value: Pre
            - name: RAINBOW_SECRET
            - name: RAINBOW_APPID
            - name: RAINBOW_USERID
            - name: REGION_NAME
              value: cq
            - name: ENABLE_CONTROLLER_MODE
              value: "true"
            - name: JAVA_OPT_EXT
              value: ' -Duser.timezone=Asia/Shanghai  -Dtls.server.mode=disabled '
            - name: TENCENT_JAVA_OPT_EXT
            - name: MEMORY_OS_ENV_GB
              valueFrom:
                resourceFieldRef:
                  containerName: rocketmq-broker
                  divisor: 1Gi
                  resource: limits.memory
            - name: TZ
              value: Asia/Shanghai
          image: registry.jiguang.woa.com/csig-tdmq/tdmq-rocketmq:tigerweili_release-2.15.1_c3db00f6e_20251121111211.rhel.amd64
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - $ROCKETMQ_HOME/shutdown.sh broker
          livenessProbe:
            failureThreshold: 600
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8911
            timeoutSeconds: 1
          name: rocketmq-broker
          readinessProbe:
            failureThreshold: 600
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8911
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /root/conf/tools.yml
              name: tdmq-config-rocketmq5-broker-tools-config
              subPath: tools.yml
            - mountPath: /data
              name: rocketmq-data
            - mountPath: /root/conf/broker.conf
              name: rocketmq-data
              subPath: conf/broker.conf
            - mountPath: /root/conf/plain_acl.yml
              name: rocketmq-data
              subPath: conf/plain_acl.yml
            - mountPath: /root/store
              name: rocketmq-data
              subPath: store
            - mountPath: /root/logs
              name: rocketmq-data
              subPath: logs
      dnsConfig:
        options:
          - name: single-request-reopen
          - name: timeout
            value: "1"
      dnsPolicy: ClusterFirst
      initContainers:
        - args:
            - |
              ./init.sh broker && echo 'init broker conf done'
              sed -i 's|^metricsExporterType=.*$|metricsExporterType=TENCENT_LOG|' /data/conf/broker.conf && echo 'update metricsExporterType done'
              sed -i 's|^innerClientAuthenticationCredentials=.*$|innerClientAuthenticationCredentials={\"accessKey\": \"ZlbUZYqqsvYaxlrZ\", \"secretKey\": \"nTAZODYPYEUaEaJy\"}|' /data/conf/broker.conf && echo 'update innerClientAuthenticationCredentials done'
              sed -i 's|^authenticationMetadataProvider=.*$|authenticationMetadataProvider=org.apache.rocketmq.auth.authentication.provider.LocalAuthenticationMetadataProvider|' /data/conf/broker.conf && echo 'update authenticationMetadataProvider done'
              sed -i 's|^metaDataServiceUrl=.*$|metaDataServiceUrl=http://ocloud-tdmq-rocketmq-manager.lb.chongqing.yfm4.fsphere.cn:81|' /data/conf/broker.conf && echo 'update metaDataServiceUrl done'
              echo 'update broker conf done' && cat /data/conf/broker.conf
          command:
            - sh
            - -c
          env:
            - name: RMQ_NS
              value: ocloud-tdmq-rocketmq5-namesrv-0.ocloud-tdmq-rocketmq5-namesrv.tce.svc.cluster.local:9876
            - name: RMQ_ID
              value: ocloud-tdmq-rocketmq5-broker
            - name: RMQ_REGION
              value: chongqing
            - name: RMQ_AK
              value: ZlbUZYqqsvYaxlrZ
            - name: RMQ_SK
              value: nTAZODYPYEUaEaJy
            - name: RMQ_TRACE_ENABLE
              value: "true"
            - name: RMQ_ACL_ENABLE
              value: "true"
            - name: RMQ_TOPIC_REGEX
              value: MQ_INST_rocketmq(.*)|rocketmq-(.*)
            - name: RMQ_ENABLE_SHARED_CLUSTER
              value: "true"
            - name: RMQ_RECOVER_CONCURRENTLY
              value: "true"
            - name: RMQ_MANAGERURL
              value: http://ocloud-tdmq-rocketmq-manager.lb.chongqing.yfm4.fsphere.cn:81
            - name: TZ
              value: Asia/Shanghai
          image: registry.jiguang.woa.com/csig-tdmq/tdmq-rocketmq:tigerweili_release-2.15.1_c3db00f6e_20251121111211.rhel.amd64
          imagePullPolicy: IfNotPresent
          name: init-data
          resources:
            limits:
              cpu: 100m
              memory: 100M
            requests:
              cpu: 100m
              memory: 100M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data
              name: rocketmq-data
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 600
      volumes:
        - configMap:
            defaultMode: 420
            name: tdmq-config-rocketmq5-broker-tools-config
          name: tdmq-config-rocketmq5-broker-tools-config
        - configMap:
            defaultMode: 420
            name: tdmq-config-rocketmq5-broker-filebeat-config
          name: tdmq-config-rocketmq5-broker-filebeat-config
        - name: rocketmq-data
          emptyDir: { }
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
